#!/usr/bin/env python3
"""Join the backbone-probe arms into one table.

Nothing else in this repo compares backbones. `run_ablation.py` emits one table
per LADDER, so four arms produce four files that nobody has put side by side,
and `readout_ceiling.py` hard-codes a three-entry tuple of banks that already
exist. Reading four `selection_probe_band_*.json` files by eye is exactly how a
5632-dim arm gets compared against a 1024-dim one without anyone noticing the
head was 5.5x bigger.

So the table carries two columns that are not results, next to the results:

  dim      the head `train_head` built. `dim_feat=bank.config["dim"]`, so a
           wider bank silently buys a bigger head, and a wide arm that wins has
           two explanations. The footnote names the control.
  dtype    what the entry declares. A `bfloat16` spec on a T4 or P100 has no
           hardware for it and `run_dtype` degrades to float32 -- same numbers,
           ~3x the time -- so a slow arm is not evidence about the tower.

Usage:

    python scripts/backbone_probe_table.py --out docs/backbone_probe_table.md
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

METRIC = "heldout_robust_tpr_at_1pct"
RUNGS = ("a0", "a1", "a2", "a3", "a7_norecon")

#: Selection files whose NAME does not carry the backbone. The local
#: crop-vs-band probe predates the `_<backbone>` suffix, so its arm is named
#: here explicitly rather than guessed at from the filename -- a wrong guess
#: would label another tower's numbers with this one's name.
LEGACY = {"docs/selection_probe_band.json": ("dinov3l", "band")}
POLICIES = ("band", "crop")


def _arms(docs_dir):
    """((backbone, policy), path) for every probe arm on disk.

    An arm is identified by BOTH, because the same tower under two
    standardisation policies is two different measurements and collapsing them
    on the backbone name alone would silently drop one.
    """
    found = {}
    for path, key in LEGACY.items():
        if os.path.exists(path):
            found[key] = path
    for path in sorted(glob.glob(os.path.join(docs_dir,
                                              "selection_probe_*.json"))):
        m = re.match(r"selection_probe_(%s)_(.+)\.json$" % "|".join(POLICIES),
                     os.path.basename(path))
        if m:
            found[(m.group(2), m.group(1))] = path
    return sorted(found.items())


def _spec(name):
    try:
        from aigcdet.features.backbones import BACKBONES
        return BACKBONES.get(name)
    except Exception:
        return None


def rows(arms):
    out = []
    for (name, policy), path in arms:
        with open(path, encoding="utf-8") as f:
            sel = json.load(f)
        summary = sel.get("summary", {})
        spec = _spec(name)
        scores = {r: summary.get(r, {}).get(METRIC) for r in RUNGS}
        scored = {r: v for r, v in scores.items() if isinstance(v, (int, float))}
        best = max(scored, key=scored.get) if scored else None
        out.append({
            "backbone": name,
            "policy": policy,
            "dim": spec.dim if spec else None,
            "params": spec.params if spec else None,
            "image_size": spec.image_size if spec else None,
            "dtype": (str(spec.dtype).replace("torch.", "") if spec else None),
            "scores": scores,
            "headline": sel.get("headline"),
            "best_rung": best,
            "best": scored.get(best) if best else None,
            "source": path,
        })
    # Best arm first: the table is read to pick one.
    return sorted(out, key=lambda r: (r["best"] is None, -(r["best"] or 0)))


def render(rows_) -> str:
    head = (["backbone", "canon", "dim", "params", "px", "dtype"] + list(RUNGS)
            + ["best rung", f"best {METRIC}"])
    lines = ["# Backbone probe: candidate towers on the 20,000-row union probe",
             "",
             "Generated by `scripts/backbone_probe_table.py`. One row per arm,",
             f"scored on `{METRIC}` -- not clean AUC.",
             "",
             "| " + " | ".join(head) + " |",
             "|" + "|".join("---" for _ in head) + "|"]
    for r in rows_:
        cells = [
            f"`{r['backbone']}`",
            r["policy"],
            str(r["dim"] or "?"),
            f"{r['params']:,}" if r["params"] else "?",
            str(r["image_size"] or "?"),
            r["dtype"] or "?",
        ]
        for rung in RUNGS:
            v = r["scores"].get(rung)
            cells.append(f"{v:.4f}" if isinstance(v, (int, float)) else "--")
        cells.append(r["best_rung"] or "--")
        cells.append(f"**{r['best']:.4f}**" if r["best"] is not None else "--")
        lines.append("| " + " | ".join(cells) + " |")

    widest = max((r for r in rows_ if r["dim"]), key=lambda r: r["dim"], default=None)
    narrowest = min((r for r in rows_ if r["dim"]), key=lambda r: r["dim"], default=None)
    lines += [
        "",
        "## Reading this table",
        "",
        "**`dim` is not a footnote.** `train_head` takes "
        "`dim_feat=bank.config[\"dim\"]`, so a wider bank is handed a bigger "
        "head and a wide arm that wins has two explanations available.",
    ]
    if widest is not None and narrowest is not None and widest["dim"] > narrowest["dim"]:
        ratio = widest["dim"] / narrowest["dim"]
        lines.append(
            f"Here `{widest['backbone']}` is {ratio:.1f}x the width of "
            f"`{narrowest['backbone']}`. If it wins, re-run the best rung of "
            f"the narrowest arm with `hidden` raised to match its head's "
            f"parameter count before calling it a finding -- a CPU-only "
            f"Stage B run of minutes.")
    lines += [
        "",
        "**`dtype` is what the entry declares.** A `bfloat16` spec on a Kaggle "
        "T4 or P100 has no hardware for it, so `run_dtype` degrades to "
        "`float32`: the same numbers at roughly 3x the time. A slow arm is "
        "evidence about the GPU, not about the tower.",
        "",
        "**Two caveats travel with every number above.**",
        "",
        "- *Scale.* 20,000 rows against the corpus's 375,358. This ranks "
        "candidates; it does not settle the shipped choice.",
        "- *Population.* Arms sourced from `docs/robustness_table.md` were "
        "measured on the frozen 138,116-row corpus, a different population "
        "from the union probe.",
        "",
        "**One pair is not an architecture comparison.** `siglip2l` keeps "
        "ImageNet normalisation because its banks were built that way, while "
        "`siglipso400m` uses SigLIP's own `[0.5]*3`. A gap between those two "
        "confounds the tower with the preprocessing "
        "(`src/aigcdet/features/backbones.py`, see `IMAGENET_MEAN`).",
        "",
        "## Arms",
        "",
    ]
    lines += [f"- `{r['backbone']}` ({r['policy']}) <- `{r['source']}`"
              for r in rows_]

    # Crop and band arms of the SAME tower answer the standardisation question,
    # not the backbone one, and reading them as a backbone comparison is the
    # mistake this block exists to pre-empt.
    by_backbone = {}
    for r in rows_:
        by_backbone.setdefault(r["backbone"], {})[r["policy"]] = r
    paired = {k: v for k, v in by_backbone.items() if len(v) > 1}
    if paired:
        lines += ["", "## Standardisation, where both policies were run", ""]
        for name, v in sorted(paired.items()):
            b, c = v.get("band"), v.get("crop")
            if b and c and b["best"] is not None and c["best"] is not None:
                lines.append(
                    f"- `{name}`: crop {c['best']:.4f} vs band {b['best']:.4f} "
                    f"(crop - band = {c['best'] - b['best']:+.4f})")
        lines += [
            "",
            "This is the STANDARDISATION comparison, not a backbone one. Read "
            "it beside the content-blind control in "
            "`docs/content_blind_probe_union.json`, which measures the other "
            "half of the same question on CPU: how much of the label survives "
            "when content is removed, per source.",
        ]
    return "\n".join(lines) + "\n"


def build_parser():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--docs-dir", default="docs")
    p.add_argument("--out", default="docs/backbone_probe_table.md")
    p.add_argument("--json-out", default=None,
                   help="also write the rows as JSON")
    return p


def main(argv=None):
    a = build_parser().parse_args(argv)
    arms = _arms(a.docs_dir)
    if not arms:
        raise SystemExit(
            f"no probe arms found. Expected "
            f"{a.docs_dir}/selection_probe_<band|crop>_<backbone>.json, written "
            f"by scripts/run_pod_arms.sh or by the ladder cell of "
            f"notebooks/kaggle_probe_<backbone>.ipynb.")
    rows_ = rows(arms)
    text = render(rows_)
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(text)
    print(f"wrote {a.out}  ({len(rows_)} arm(s))")
    if a.json_out:
        with open(a.json_out, "w", encoding="utf-8") as f:
            json.dump(rows_, f, indent=2)
        print(f"wrote {a.json_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
