"""Which reals are eligible, and which family generates each one.

Two jobs, both pure enough to test without a GPU:

1. **Eligibility.** A real is eligible only if its JPEG encoder can be
   reproduced onto its fake (`encode.reproducible_encoder`) and it survives the
   MCU-aligned crop at a sane size. Ineligibility is recorded with a reason
   rather than filtered silently, because "8.4% of the pool vanished" is a
   thing a later reader needs to be able to explain.

2. **Assignment.** One real produces exactly one fake, for exactly one family
   (`PAIRING = "disjoint"`). The alternative -- the same real generated by
   several families -- would put the same scene in the corpus 4 or 5 times on
   the fake side against one real, and any content the detector memorises then
   carries a label prior.
"""
from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd

from aigcdet.generate.encode import reproducible_encoder, source_encoder
from aigcdet.generate.geometry import MAX_SIDE, MCU_ALIGN, MIN_SIDE, order_key, shard_block

#: Columns `run.py` needs off a pool row. Named here so a schema change breaks
#: loudly at import rather than at row 9,000 of a six-hour run.
POOL_COLUMNS = ("image_id", "path", "width", "height", "crop_l", "crop_t",
                "crop_r", "crop_b", "subsampling", "jpeg_quality", "mode",
                "eligible", "reason")


def _probe(path: Path, min_side: int, mcu: int, max_side: int) -> dict:
    """Header-only probe of one real. Never decodes pixels."""
    from aigcdet.generate.geometry import crop_box
    row = {"image_id": path.stem, "path": str(path), "width": 0, "height": 0,
           "crop_l": 0, "crop_t": 0, "crop_r": 0, "crop_b": 0,
           "subsampling": -1, "jpeg_quality": float("nan"), "mode": "",
           "eligible": False, "reason": ""}
    try:
        enc = source_encoder(path)
    except Exception as exc:                       # unreadable, truncated, not JPEG
        row["reason"] = f"unreadable: {type(exc).__name__}"
        return row
    w, h = enc["size"]
    row.update(width=w, height=h, subsampling=enc["subsampling"],
               jpeg_quality=enc["jpeg_quality"], mode=enc["mode"])
    if min(w, h) < min_side:
        row["reason"] = f"short side {min(w, h)} < {min_side}"
        return row
    if not reproducible_encoder(enc):
        row["reason"] = (f"encoder not reproducible (mode={enc['mode']}, "
                         f"subsampling={enc['subsampling']}, "
                         f"{len(enc['qtables'])} qtable(s))")
        return row
    try:
        l, t, r, b = crop_box(w, h, mcu=mcu, max_side=max_side)
    except ValueError as exc:
        row["reason"] = str(exc)
        return row
    if min(r - l, b - t) < min_side:
        row["reason"] = f"cropped short side {min(r - l, b - t)} < {min_side}"
        return row
    row.update(crop_l=l, crop_t=t, crop_r=r, crop_b=b, eligible=True)
    return row


def build_pool(portrait_dir: str | Path, attribution_csv: str | Path,
               *, min_side: int = MIN_SIDE, mcu: int = MCU_ALIGN,
               max_side: int = MAX_SIDE, workers: int = 16) -> pd.DataFrame:
    """Probe every real, join the attribution, return one row per file.

    The CC BY 2.0 check is an assertion, not a filter. `docs/02` §1 is explicit
    that CC BY 2.0 -- commercial use *and* redistribution with attribution --
    is the whole reason this source was chosen over Pexels or Unsplash, so a
    row under any other licence means the harvest changed and the run should
    stop, not quietly shrink.
    """
    portrait_dir = Path(portrait_dir)
    attr = pd.read_csv(attribution_csv)
    bad = attr.loc[attr["License"] != "https://creativecommons.org/licenses/by/2.0/"]
    if len(bad):
        raise ValueError(
            f"{len(bad)} attribution rows are not CC BY 2.0 (e.g. "
            f"{bad['License'].iloc[0]!r}). docs/02 §1: CC BY 2.0 is the only "
            f"licence audited to clear both commercial use and redistribution. "
            f"Do not silently substitute another.")
    for col in ("Author", "OriginalURL"):
        n = int(attr[col].isna().sum())
        if n:
            raise ValueError(f"{n} attribution rows have a blank {col}; CC BY "
                             f"requires attribution and docs/02 §5.4 gates on it")

    files = sorted(portrait_dir.glob("*.jpg"))
    if not files:
        raise FileNotFoundError(f"no *.jpg under {portrait_dir}")
    with ThreadPoolExecutor(workers) as ex:
        rows = list(ex.map(lambda p: _probe(p, min_side, mcu, max_side), files))
    pool = pd.DataFrame(rows)[list(POOL_COLUMNS)]

    known = set(attr["ImageID"].astype(str))
    missing = ~pool["image_id"].isin(known)
    if missing.any():
        pool.loc[missing, "eligible"] = False
        pool.loc[missing, "reason"] = "no attribution row"
    return pool


def rebase_paths(pool: pd.DataFrame, portrait_dir: str | Path,
                 *, check: int = 5) -> pd.DataFrame:
    """Re-point a cached pool's `path` column at THIS box's copy of the reals.

    `build_pool` writes absolute paths, and `run.run_family` opens `row.path`
    directly. So a `ov7_pool.parquet` built on the harvest box and staged onto
    a rented one names files that do not exist there: every row raises
    FileNotFoundError, and `run_family`'s runaway-failure guard stops the run
    -- correctly, but forty images late and with a reason that reads like a
    corrupt pool rather than a moved directory.

    Rebasing on the BASENAME is safe here because the pool is one flat
    directory of `<ImageID>.jpg` and `image_id` is the stem; there is no tree
    to preserve. A no-op when the paths already point at `portrait_dir`, so it
    costs nothing on the box that built the pool.
    """
    portrait_dir = Path(portrait_dir).resolve()
    if not len(pool):
        return pool
    parents = {str(Path(p).parent) for p in pool["path"].head(1000)}
    if parents == {str(portrait_dir)}:
        return pool
    out = pool.copy()
    out["path"] = [str(portrait_dir / Path(p).name) for p in out["path"]]
    # Fail here, on five files, rather than at row 40 of a six-hour run.
    sample = list(out.loc[out["eligible"], "path"].head(check))
    missing = [q for q in sample if not Path(q).exists()]
    if missing:
        raise FileNotFoundError(
            f"rebased the cached pool onto {portrait_dir} but "
            f"{len(missing)} of the first {len(sample)} eligible reals are "
            f"not there (e.g. {missing[0]}). The pool was built against "
            f"{sorted(parents)[0]}; stage the reals or pass the right "
            f"--portrait-dir.")
    return out


#: Coarsest granularity of the share strata. The ordered pool is dealt to
#: families in repeating blocks of this length, so any prefix of the order
#: carries the suite's shares to within one block.
#:
#: It is a FLOOR, not the value used: `_strata_len` refines it to whatever the
#: suite's shares actually need. At 100 a share is quantised to 1%, which is
#: exact for the original suite (.30/.20/.14/.10/.08/.12/.06) and wrong for
#: `ov7_full`, whose shares are solved to four decimals (.0938, .0146, .0104).
#: There the pattern allotted `klein4b_t2i` 9 slots per 100 -- 3,843 of the
#: pool -- while `resolve_suite` had asked for 4,000 by largest remainder, and
#: `select` refused the deal. The two disagreed because they quantised the same
#: shares differently, so the fix is to stop quantising in `_strata`.
STRATA = 100

#: How far `_strata_len` will refine before giving up.
STRATA_MAX = 1_000_000


def _strata_len(shares: dict[str, float], floor: int = STRATA,
                cap: int = STRATA_MAX) -> int:
    """Smallest 10x multiple of `floor` on which every share is a whole number.

    Derived from the SHARES ALONE and never from `--total`, which is what keeps
    the deal prefix-stable: the pattern a run uses must not depend on how many
    images that run asked for, or `--total 3000` stops being a strict prefix of
    `--total 10000` and reals already generated get reassigned.
    """
    k = floor
    while k <= cap:
        if all(abs(v * k - round(v * k)) < 1e-6 for v in shares.values()):
            return k
        k *= 10
    return cap


def _strata(shares: dict[str, float], k: int | None = None) -> list[str]:
    """A length-`k` deal pattern realising `shares`, INTERLEAVED.

    Interleaved is the whole point and it was the bug. This used to emit each
    family's slots contiguously (`out += [name] * counts[name]`, families in
    alphabetical order), so a period looked like AAAA...BBBB...CCCC. That is
    only balanced when the pool is an exact multiple of `k`: over 42,646 reals
    with `k=10000` the last period is 26% long, the tail covers only the
    alphabetically-early families, and `wuerstchen_t2i` came out 7,324 against
    the 7,808 `resolve_suite` had asked for.

    So slots are dealt one at a time to whichever family is furthest behind its
    share -- Hamilton apportionment run incrementally, the same rule
    `resolve_suite` uses. Every PREFIX of the pattern then carries the suite's
    shares to within one slot per family, which is what makes `--total 3000` a
    strict prefix of `--total 10000` rather than a reshuffle, and what makes a
    run cut short still balanced across families instead of missing whole ones.
    """
    if k is None:
        k = _strata_len(shares)
    given = {n: 0 for n in shares}
    out: list[str] = []
    for i in range(1, k + 1):
        # The family whose entitlement at this point most exceeds what it has.
        name = max(shares, key=lambda n: (shares[n] * i - given[n], -ord(n[0]), n))
        given[name] += 1
        out.append(name)
    return out


def select(pool: pd.DataFrame, counts: dict[str, int], *, seed: int,
           shard: int = 0, n_shards: int = 1,
           shares: dict[str, float] | None = None) -> pd.DataFrame:
    """Assign eligible reals to families, disjointly and **prefix-stably**.

    Order is `blake2b(seed, image_id)` -- a property of the image, not of the
    directory listing or of how many rows the pool happened to have -- so the
    same real lands in the same family on a rerun, and a shard is a contiguous
    block of that order rather than a comb across the pool.

    The family deal is a repeating stratum pattern over that order, NOT a
    contiguous slice per family. That distinction is what makes the run
    resumable at a different `--total`: with contiguous slices, raising the
    total moves every family boundary and reassigns reals that have already
    been generated, so the earlier work is orphaned rather than resumed. With
    strata, `--total 3000` is a strict prefix of `--total 10000`, every prefix
    carries the suite's shares, and a run cut short is still balanced across
    families instead of missing whole ones.

    One real produces exactly one fake for exactly one family. The alternative
    -- the same real generated by several families -- would put one scene in
    the corpus four or five times on the fake side against one real, and any
    content the detector memorises then carries a label prior.
    """
    if not counts:
        raise ValueError("no families requested")
    if shares is None:
        total = sum(counts.values())
        shares = {n: c / total for n, c in counts.items()}

    elig = pool.loc[pool["eligible"]].copy()
    elig["order_key"] = [order_key(i, seed) for i in elig["image_id"]]
    elig = elig.sort_values("order_key", kind="mergesort").reset_index(drop=True)

    start, stop = shard_block(len(elig), shard, n_shards)
    block = elig.iloc[start:stop].reset_index(drop=True)
    need = sum(counts.values())
    if len(block) < need:
        raise ValueError(
            f"shard {shard}/{n_shards} has {len(block)} eligible reals but the "
            f"suite asks for {need}. Lower --total or widen the pool "
            f"({int(pool['eligible'].sum())} eligible of {len(pool)} probed).")

    pattern = _strata(shares)
    block["family"] = [pattern[i % len(pattern)] for i in range(len(block))]

    out = []
    for name, n in sorted(counts.items()):
        part = block.loc[block["family"] == name]
        if len(part) < n:
            raise ValueError(
                f"{name}: the pool yields {len(part)} strata slots but {n} were "
                f"asked for. The block holds {len(block)} reals and the stratum "
                f"pattern is length {len(pattern)}. If {len(part)} is close to "
                f"{n}, the shares are finer than the pattern can express and "
                f"`_strata_len` needs to refine further; if it is far short, "
                f"the pool is genuinely too small for this share.")
        out.append(part.iloc[:n])
    sel = pd.concat(out, ignore_index=True)
    if sel["image_id"].duplicated().any():
        raise AssertionError("a real was assigned to more than one family; "
                             "pairing is meant to be disjoint")
    return sel
